name: Enforce branch naming convention

on:
  pull_request:
    branches: [ main ]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix)/[a-z0-9._-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' is invalid. Use feature/, bugfix/, or hotfix/ prefix."
            exit 1
          fi
          echo "Branch name '$BRANCH_NAME' is valid."
