name: Java CI

on:
  push:
    branches:
      - devbranch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & run tests
        run: mvn -B clean verify

      - name: Run Checkstyle
        run: mvn -B checkstyle:check
